/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DashboardStats {
  'totalProjects' : bigint,
  'totalLeads' : bigint,
  'totalAIGenerations' : bigint,
  'totalScheduledPosts' : bigint,
}
export interface Lead {
  'id' : string,
  'status' : string,
  'source' : string,
  'name' : string,
  'workspaceId' : string,
  'phone' : string,
}
export interface Project {
  'id' : string,
  'status' : string,
  'clientId' : string,
  'name' : string,
  'workspaceId' : string,
}
export interface ScheduledPost {
  'id' : string,
  'status' : string,
  'content' : string,
  'platform' : string,
  'workspaceId' : string,
  'scheduledAt' : bigint,
}
export interface UserProfile {
  'name' : string,
  'role' : string,
  'email' : string,
  'workspaceId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workspace {
  'id' : string,
  'owner' : Principal,
  'name' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeImage' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createLead' : ActorMethod<[string, string, string], string>,
  'createProject' : ActorMethod<[string, string, string], string>,
  'createWorkspace' : ActorMethod<[string], string>,
  'generateAIText' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMe' : ActorMethod<[], [] | [UserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkspace' : ActorMethod<[string], [] | [Workspace]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listLeads' : ActorMethod<[], Array<Lead>>,
  'listProjects' : ActorMethod<[], Array<Project>>,
  'listScheduledPosts' : ActorMethod<[], Array<ScheduledPost>>,
  'loginUser' : ActorMethod<[string, string], string>,
  'registerUser' : ActorMethod<
    [string, string, string, string, string],
    string
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schedulePost' : ActorMethod<[string, string, bigint], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];