/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Text,
  'email' : IDL.Text,
  'workspaceId' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'totalProjects' : IDL.Nat,
  'totalLeads' : IDL.Nat,
  'totalAIGenerations' : IDL.Nat,
  'totalScheduledPosts' : IDL.Nat,
});
export const Workspace = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
});
export const Lead = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'source' : IDL.Text,
  'name' : IDL.Text,
  'workspaceId' : IDL.Text,
  'phone' : IDL.Text,
});
export const Project = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'clientId' : IDL.Text,
  'name' : IDL.Text,
  'workspaceId' : IDL.Text,
});
export const ScheduledPost = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'content' : IDL.Text,
  'platform' : IDL.Text,
  'workspaceId' : IDL.Text,
  'scheduledAt' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeImage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'createWorkspace' : IDL.Func([IDL.Text], [IDL.Text], []),
  'generateAIText' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMe' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkspace' : IDL.Func([IDL.Text], [IDL.Opt(Workspace)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'listScheduledPosts' : IDL.Func([], [IDL.Vec(ScheduledPost)], ['query']),
  'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schedulePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Text,
    'email' : IDL.Text,
    'workspaceId' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'totalProjects' : IDL.Nat,
    'totalLeads' : IDL.Nat,
    'totalAIGenerations' : IDL.Nat,
    'totalScheduledPosts' : IDL.Nat,
  });
  const Workspace = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
  });
  const Lead = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'source' : IDL.Text,
    'name' : IDL.Text,
    'workspaceId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Project = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'clientId' : IDL.Text,
    'name' : IDL.Text,
    'workspaceId' : IDL.Text,
  });
  const ScheduledPost = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'content' : IDL.Text,
    'platform' : IDL.Text,
    'workspaceId' : IDL.Text,
    'scheduledAt' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeImage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createLead' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createProject' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'createWorkspace' : IDL.Func([IDL.Text], [IDL.Text], []),
    'generateAIText' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMe' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkspace' : IDL.Func([IDL.Text], [IDL.Opt(Workspace)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'listProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'listScheduledPosts' : IDL.Func([], [IDL.Vec(ScheduledPost)], ['query']),
    'loginUser' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schedulePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };